Soacial/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.views import HomeView,TestPage,ThanksPage
urlpatterns = [
    path('', HomeView.as_view(),name="home"),
    path('test/', TestPage.as_view(),name="test"),
    path('thanks/', ThanksPage.as_view(),name="thanks"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace="accounts")),

    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    
    path('signup/', views.SignUp.as_view(),name="signup"),


]

accounts/models.py
from django.db import models

# Create your models here.

groups/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


class HomeView(TemplateView):
    template_name = "index.html"



class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

class TestPage(TemplateView):
    template_name = "test.html"

class ThanksPage(TemplateView):
    template_name = "thanks.html"

class LoginView(TemplateView):
    template_name = "accounts/login.html"

groups/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<div class="container">


<h2>Sign up</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Sign up</button>
  </form>
</div>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en-us">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <title>Page Title</title>

</head>
<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="{% url "home" %}">Social</a>

    <!-- Links -->
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="#">Post </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Group</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Create Group</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "logout" %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="#">Groups </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "login" %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:signup" %}"> Sign Up</a>
      </li>
      {% endif %}

    </ul>
  </nav>
  <div class="container">
    {% block content%}
    {% endblock %}

  </div>

</body>
</html>

templates/index.html
{% extends "base.html"%}

{% block content%}
{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block content %}
<div class="container">


<h2>You are now Log In </h2>

</div>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}

{% block content %}
<div class="container">


<h2>Thanks for visiting</h2>

</div>

{% endblock %}